code review Andries
hunterkoppenclevr/mention-input-widget pull request #2
Opened 2022-01-04 22:33 UTC by hunterkoppenclevr

2022-01-05 16:05 UTC, Andries-Smit requested changes
Let us discuss next time

2022-01-05 16:05 UTC, Andries-Smit commented on package.json
> +  "copyright": "2021 CLEVR B.V.",
```suggestion
  "copyright": "2021 CLEVR NL B.V.",
```

2022-01-05 16:05 UTC, Andries-Smit commented on package.json
> +    "@draft-js-plugins/mention": "^5.1.0",
Let's discuss how to select libraries, draft-js is 'dead' luckily the plugins in the community are still alive.

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +// react mentions library
remove comments

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +    constructor(props) {
constructor can be removed

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +import data from "./data/google";
Names does not explain the content, 
rename to `emoji`

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +        if (prevProps && prevProps === this.props) {
removed unused code

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +            // Props still empty
remove

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +            // check if widget is readonly
Make it a good habit to start comment with a capital

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +            if (prevProps.valueAttribute.value !== this.props.valueAttribute.value) {
props derived from state is a bit of an anti pattern, and not always needed https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +                this.props.onChangeAction.execute();
on change is not always needed to be set. look at the alternative attribute onChange attribute
https://docs.mendix.com/apidocs-mxsdk/apidocs/pluggable-widgets-property-types#attribute

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +}
Best practises, to split this file in an API Wrapper/container with Mendix, and the implementation of the widget. This allows you the split the Mendix API from. One part deals with the UI component, one part deals with the Mendix APIs
lets discuss with some samples

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +        if (this.props.renderMode === "textbox") {
props desctructuring will allows you not to releat this.props.... al the time
``` ts
const { emojiPickerTheme, autoFocusSearch, emojiTopbarColor } = this.props;
```

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +        <div className={`user ${focused ? "focused" : ""}`}>{suggestion.content}</div>
Use `classNames` for building CSS classes
``` js
classNames("user", {"focused": focused })
```
https://www.npmjs.com/package/classnames

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +import data from "./data/google";
its also a bit big for a widget  861 KB Do you need it all?

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +            const content = this.props.suggestionContent ? this.props.suggestionContent.get(mxObject) : objLabel;
typescript would make this nicer. maybe it works in js too?
``` ts
this.props.suggestionContent?.get(mxObject) ?? objLabel;
```

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +                content: content
```suggestion
                content
```
short hand notation preferred

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +            JSON.stringify(this.state.mentions) != JSON.stringify(mentions) // eslint-disable-line
complex if statements should be simplified. for by extracting it into a function
`if (isChanged(this.state.mentions, mentions)) {`

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +            mentions: mentions
```suggestion
            mentions
```

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +        }
remove else bloc just
``` js
if (this.props.keepTriggerSymbol) {
     return this.props.mentionTrigger + display;
}
return display;
```

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +            if (mxObjectToAdd && mxObjectToAdd.id != null) {
`mxObjectToAdd.id != null` can this happen after the find above? you check `&& mention` above so it can not be `null`

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +    convertTextToEmojis = text => {
mixing variable function with class function is not pretty

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +                <div ref={this.nodeRef} className="mentionsReadOnly">
best practice for styling to give the root of the widget a class name suggestion: `mx-widget-mentions` allowing to add styles later on all nodes

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +                <div ref={this.nodeRef} style={{ position: "relative" }}>
move inline style to CSS

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.jsx
> +                        <button className={"emoji__button"} onClick={() => this.setState({ showEmojis: true })}>
it is prettier to have no function defined in the jsx

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.xml
> +            </propertyGroup>
suggestion to add `<systemProperty key="Label"/>` prop too

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.xml
> +                <property key="valueAttribute" type="attribute" required="true">
required is default true, so can be removed when `true`

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.xml
> +                    <description></description>
```suggestion
                    <description/>
```
no need for empty tags

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.xml
> +    <description>Textbox widget for mentioning someone or something in the textarea itself based on a dropdown. Like when using @ in Slack or Teams.</description>
```suggestion
    <description/>
```
widget.description is no where used in the platform and should be removed

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.xml
> +    <icon> iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QA/wD/AP+gvaeTAAAG6klEQVRoge1a3W8bVRY/dzwzdjJjz8T2+HrGM/ZMClHUNv2gW3ArFdqsADXQBpVWsKtqm0qrTapunVA7QeVp3lb7IVgBYov2hf4Bu9rVSogPlQdUAWIl
remove space before i =>  `<icon>i`

2022-01-05 16:05 UTC, Andries-Smit commented on src/MentionInputWidget.xml
> +            <propertyGroup caption="Events">
move to tab events

2022-01-05 16:05 UTC, Andries-Smit commented on src/ui/MentionInputWidget.css
> +    /* unused */
use SCSS
All wrapped in container class `mx-widget-mentions` to prevent conflicts with other widget and styling in the app

2022-01-05 16:05 UTC, Andries-Smit commented on LICENSE
> +Copyright 2021 CLEVR B.V.
```suggestion
Copyright 2021 CLEVR NL B.V.
```

2022-01-11 20:53 UTC, hunterkoppenclevr commented on package.json
> +    "@draft-js-plugins/mention": "^5.1.0",
Draft JS was used in an earlier version of the widget but isnt needed anymore and therefor has been removed.

2022-01-11 21:15 UTC, hunterkoppenclevr commented on src/MentionInputWidget.jsx
> +import data from "./data/google";
Renamed import, file is needed for all the different emoji's that are available, Ill see if I can compress is some more.

2022-01-20 21:25 UTC, hunterkoppenclevr commented on src/MentionInputWidget.xml
> +            </propertyGroup>
This breaks my datasource parameter in the addmentionaction for some reason. Should make a support ticket for this. Looks like I'm not the only one, see last comment on https://forum.mendixcloud.com/link/questions/105520

2022-01-20 22:01 UTC, hunterkoppenclevr commented on src/MentionInputWidget.jsx
> +                this.props.onChangeAction.execute();
In this case its needed because I dont want it to trigger with each letter typed but only when leaving the input and something has changed.

2022-11-10 12:48 UTC, closed without merging